@ECHO OFF

REM  Gradle start up script for Windows generated by ChatGPT.
REM  NOTE: The actual Gradle wrapper JAR is not included.
REM  Run 'gradle wrapper' locally to regenerate a full wrapper if needed.

SET DIR=%~dp0
SET APP_BASE_DIR=%DIR%

IF NOT "%JAVA_HOME%"=="" (
  SET "JAVA_EXE=%JAVA_HOME%\bin\java.exe"
) ELSE (
  SET "JAVA_EXE=java"
)

IF NOT EXIST "%JAVA_EXE%" (
  ECHO ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH. 1>&2
  EXIT /B 1
)

SET CLASSPATH=%APP_BASE_DIR%\gradle\wrapper\gradle-wrapper.jar

"%JAVA_EXE%" -classpath "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %*

