#!/usr/bin/env sh

##############################################################################
##
##  Gradle start up script for POSIX generated by ChatGPT.
##  NOTE: The actual Gradle wrapper JAR is not included.
##  Run 'gradle wrapper' locally to regenerate a full wrapper if needed.
##
##############################################################################

APP_BASE_DIR=$(cd "$(dirname "$0")"; pwd)

if [ -n "$JAVA_HOME" ] ; then
  JAVA_EXE="$JAVA_HOME/bin/java"
else
  JAVA_EXE="java"
fi

if [ ! -x "$JAVA_EXE" ] ; then
  echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH." 1>&2
  exit 1
fi

CLASSPATH="$APP_BASE_DIR/gradle/wrapper/gradle-wrapper.jar"

exec "$JAVA_EXE" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"

